let shopItemsData = [
    {
        id: "jfhgbvnscs",
        name: "Lorem ipsum",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.jpg",
    },
    {
        id: "ioytrhndcv",
        name: "Lorem ipsum",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.jpg",
    },
    {
        id: "wuefbncxbsn",
        name: "Lorem ipsum",
        price: 199,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-3.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Lorem ipsum",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.jpg",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Lorem ipsum",
        price: 199,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-3.jpg",
    },
    {
        id: "iuertrywebncdjksadjk",
        name: "Lorem ipsum",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-1.jpg",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "Lorem ipsum",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.jpg",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "Lorem ipsum",
        price: 445,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.jpg",
    },
    {
        id: "cbvxbcvsceldk",
        name: "Lorem ipsum",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.jpg",
    },
    {
        id: "oiopijmjkhuihb",
        name: "Lorem ipsum",
        price: 399,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-2.jpg",
    },
    {
        id: "oiopijewyiohbjhib",
        name: "Lorem ipsum",
        price: 299,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-1.jpg",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "Lorem ipsum",
        price: 799,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-2.jpg",
    },
];
